#!/bin/bash

# sudo wget https://raw.githubusercontent.com/CarloseOldenburg/updater/refs/heads/main/ferramentas -O vsd-launcher && sudo chmod 755 vsd-launcher && sudo mv vsd-launcher /usr/bin/

function display_help() {
    echo "Uso: vsd-launcher -s <software> [-v <version>] [--homolog] [--clear-cache] [--clear-token]"
    echo "Consulte a documentação para mais detalhes."
}

function update_url() {
    local service=""
    local version=""
    local homolog=false
    local new_url=""
    local clear_cache_flag=false
    local clear_token_flag=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            -s)
                service=$2
                shift 2
                ;;
            -v)
                version=$2
                shift 2
                ;;
            --homolog)
                homolog=true
                shift
                ;;
            --clear-cache)
                clear_cache_flag=true
                shift
                ;;
            --clear-token)
                clear_token_flag=true
                shift
                ;;
            -h|--help)
                display_help
                exit 0
                ;;
            *)
                echo "Opção inválida: $1" >&2
                display_help
                exit 1
                ;;
        esac
    done

    # Executa limpeza se solicitado
    if [ "$clear_token_flag" = true ]; then
        clear_token
        exit 0
    elif [ "$clear_cache_flag" = true ]; then
        clear_cache
        exit 0
    fi

    # Verifica se o serviço foi informado para operações que dependem disso
    if [ -z "$service" ]; then
        echo "Serviço não especificado. Utilize a opção -s." >&2
        exit 1
    fi

    if [ "$service" == "food" ]; then
        if [ "$version" == "2" ]; then
            if [ "$homolog" = true ]; then
                new_url="https://food2.homolog.vsd.app"
            else
                new_url="https://food2.vsd.app"
            fi
        elif [ "$version" == "3" ] || [ -z "$version" ]; then
            if [ "$homolog" = true ]; then
                new_url="https://food.homolog.vsd.app"
            else
                new_url="https://food.vsd.app"
            fi
        else
            echo "Versão desconhecida para o serviço 'food'." >&2
            exit 1
        fi
    elif [ "$service" == "self" ]; then
        if [ "$homolog" = true ]; then
            new_url="https://selfcheckout.homolog.vsd.app"
        else
            new_url="https://selfcheckout.vsd.app"
        fi
    else
        echo "Serviço desconhecido." >&2
        exit 1
    fi

    sudo sed -i "s|^VS_URL_APP=.*|VS_URL_APP=\"$new_url\"|" /opt/videosoft/vs-food-launcher/app/vs-food.sh

    echo "URL atualizada para: $new_url"
}

function clear_cache() {
    rm -rf ~/.cache/google-chrome/*
    rm -rf ~/.config/google-chrome/*
    echo "Cache do Google Chrome limpo."
}

function clear_token() {
    rm -rf ~/.cache/google-chrome/*
    rm -rf ~/.config/google-chrome/*
    echo "Cache do Google Chrome limpo."

    sudo rm -f /opt/videosoft/vs-os-interface/log/_database_token* && echo "Arquivo _database_token* excluído."
    sudo rm -f /opt/videosoft/vs-os-interface/log/_database_recovery* && echo "Arquivo _database_recovery* excluído."

    echo "Token e cache do Google Chrome limpos."
}

if [ $# -eq 0 ]; then
    display_help
    exit 0
fi

update_url "$@"
